/**
 * Notification type constants
 * Tập trung tất cả notification types để tránh magic strings
 */
export const NotificationType = {
  EVALUATION: 'EVALUATION',
  EVALUATION_SUPERVISOR1: 'EVALUATION_SUPERVISOR1',
  EVALUATION_SUPERVISOR1_COMPLETED: 'EVALUATION_SUPERVISOR1_COMPLETED',
  EVALUATION_SUPERVISOR2: 'EVALUATION_SUPERVISOR2',
  EVALUATION_COMPLETED: 'EVALUATION_COMPLETED',
  TASK: 'TASK',
  LEAVE_REQUEST: 'LEAVE_REQUEST',
  LEAVE_REQUEST_RESPONSE: 'LEAVE_REQUEST_RESPONSE',
  PAYROLL: 'PAYROLL',
  ACCEPTANCE_HANDOVER: 'ACCEPTANCE_HANDOVER',
  OVERTIME_PLAN: 'OVERTIME_PLAN',
  OVERTIME_PLAN_APPROVAL: 'OVERTIME_PLAN_APPROVAL',
  SUPPLY_REQUEST: 'SUPPLY_REQUEST',
  SUPPLY_REQUEST_PROCESSING: 'SUPPLY_REQUEST_PROCESSING',
  SUPPLY_REQUEST_APPROVED: 'SUPPLY_REQUEST_APPROVED',
  SUPPLY_REQUEST_FULFILLED: 'SUPPLY_REQUEST_FULFILLED',
  PASSWORD_RESET: 'PASSWORD_RESET',
  TASK_ADMIN: 'TASK_ADMIN',
  PRIVATE_FEEDBACK: 'PRIVATE_FEEDBACK',
  DAILY_WORK_REPORT: 'DAILY_WORK_REPORT',
  WORK_PLAN: 'WORK_PLAN',
  REPAIR_REQUEST: 'REPAIR_REQUEST',
  PURCHASE_REQUEST: 'PURCHASE_REQUEST',
  ORDER: 'ORDER',
  WAREHOUSE: 'WAREHOUSE',
  INVOICE: 'INVOICE',
  DEBT: 'DEBT',
  PRODUCTION_REPORT: 'PRODUCTION_REPORT',
  PROJECT_APPROVAL: 'PROJECT_APPROVAL',
} as const;

export type NotificationType = typeof NotificationType[keyof typeof NotificationType];

/**
 * Notification events — business events that trigger notifications.
 * Each event maps to a registry entry with message template + recipient resolver.
 */
export const NotificationEvent = {
  // Evaluation
  EVALUATION_CREATED: 'EVALUATION_CREATED',
  EVALUATION_SUPERVISOR1_PENDING: 'EVALUATION_SUPERVISOR1_PENDING',
  EVALUATION_SUPERVISOR2_PENDING: 'EVALUATION_SUPERVISOR2_PENDING',
  EVALUATION_SUPERVISOR1_COMPLETED: 'EVALUATION_SUPERVISOR1_COMPLETED',
  EVALUATION_COMPLETED: 'EVALUATION_COMPLETED',
  // Task
  TASK_ASSIGNED: 'TASK_ASSIGNED',
  TASK_ADMIN_COPY: 'TASK_ADMIN_COPY',
  // Leave
  LEAVE_REQUEST_SUBMITTED: 'LEAVE_REQUEST_SUBMITTED',
  LEAVE_REQUEST_RESPONDED: 'LEAVE_REQUEST_RESPONDED',
  // Payroll
  PAYROLL_PUBLISHED: 'PAYROLL_PUBLISHED',
  // Acceptance handover
  ACCEPTANCE_HANDOVER_CREATED: 'ACCEPTANCE_HANDOVER_CREATED',
  // Overtime
  OVERTIME_PLAN_SUBMITTED: 'OVERTIME_PLAN_SUBMITTED',
  OVERTIME_PLAN_RESPONDED: 'OVERTIME_PLAN_RESPONDED',
  OVERTIME_PLAN_APPROVED_PARTICIPANT: 'OVERTIME_PLAN_APPROVED_PARTICIPANT',
  OVERTIME_PLAN_REJECTED_PARTICIPANT: 'OVERTIME_PLAN_REJECTED_PARTICIPANT',
  // Supply / purchase
  SUPPLY_REQUEST_CREATED: 'SUPPLY_REQUEST_CREATED',
  SUPPLY_REQUEST_PROCESSING: 'SUPPLY_REQUEST_PROCESSING',
  SUPPLY_REQUEST_APPROVED: 'SUPPLY_REQUEST_APPROVED',
  SUPPLY_REQUEST_FULFILLED: 'SUPPLY_REQUEST_FULFILLED',
  // Auth
  PASSWORD_RESET_REQUESTED: 'PASSWORD_RESET_REQUESTED',
  // Feedback / reports
  PRIVATE_FEEDBACK_SUBMITTED: 'PRIVATE_FEEDBACK_SUBMITTED',
  DAILY_WORK_REPORT_SUBMITTED: 'DAILY_WORK_REPORT_SUBMITTED',
  WORK_PLAN_ASSIGNED: 'WORK_PLAN_ASSIGNED',
  // Technical
  REPAIR_REQUEST_CREATED: 'REPAIR_REQUEST_CREATED',
  REPAIR_REQUEST_UPDATED: 'REPAIR_REQUEST_UPDATED',
  // Purchase request (notify requester)
  PURCHASE_REQUEST_APPROVED: 'PURCHASE_REQUEST_APPROVED',
  PURCHASE_REQUEST_REJECTED: 'PURCHASE_REQUEST_REJECTED',
  PURCHASE_REQUEST_COMPLETED: 'PURCHASE_REQUEST_COMPLETED',
  // Order / warehouse / accounting
  ORDER_CREATED: 'ORDER_CREATED',
  ORDER_STATUS_UPDATED: 'ORDER_STATUS_UPDATED',
  WAREHOUSE_RECEIPT_CREATED: 'WAREHOUSE_RECEIPT_CREATED',
  WAREHOUSE_ISSUE_CREATED: 'WAREHOUSE_ISSUE_CREATED',
  INVOICE_CREATED: 'INVOICE_CREATED',
  DEBT_CREATED: 'DEBT_CREATED',
  PRODUCTION_REPORT_CREATED: 'PRODUCTION_REPORT_CREATED',
  MACHINE_ACTIVITY_REPORTED: 'MACHINE_ACTIVITY_REPORTED',
  // Project approval
  PROJECT_APPROVAL_SUBMITTED: 'PROJECT_APPROVAL_SUBMITTED',
  PROJECT_APPROVAL_APPROVED: 'PROJECT_APPROVAL_APPROVED',
  PROJECT_APPROVAL_REJECTED: 'PROJECT_APPROVAL_REJECTED',
} as const;

export type NotificationEvent = typeof NotificationEvent[keyof typeof NotificationEvent];

/**
 * Context passed to event registry for building messages and resolving recipients.
 */
export interface NotificationContext {
  actorUserId?: string;
  targetEmployeeIds?: string[];
  entityId?: string;
  metadata?: Record<string, unknown>;
}

/**
 * Registry entry — defines how a notification event is handled.
 */
export interface NotificationEventDef {
  event: NotificationEvent;
  notificationType: NotificationType;
  buildMessage: (ctx: NotificationContext) => { title: string; message: string };
  resolveRecipients: (ctx: NotificationContext) => Promise<string[]>;
}

/**
 * Evaluation status constants
 * Tập trung tất cả evaluation statuses để tránh magic strings
 */
export const EvaluationStatus = {
  SELF_PENDING: 'SELF_PENDING',
  SUPERVISOR1_PENDING: 'SUPERVISOR1_PENDING',
  SUPERVISOR2_PENDING: 'SUPERVISOR2_PENDING',
  COMPLETED: 'COMPLETED',
  ACKNOWLEDGED: 'ACKNOWLEDGED',
} as const;

export type EvaluationStatus = typeof EvaluationStatus[keyof typeof EvaluationStatus];

/**
 * Leave request status constants
 */
export const LeaveRequestStatusConst = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
} as const;

export type LeaveRequestStatusConst = typeof LeaveRequestStatusConst[keyof typeof LeaveRequestStatusConst];

