/**
 * Notification type constants
 * Tập trung tất cả notification types để tránh magic strings
 */
export const NotificationType = {
  EVALUATION: 'EVALUATION',
  EVALUATION_SUPERVISOR1: 'EVALUATION_SUPERVISOR1',
  EVALUATION_SUPERVISOR2: 'EVALUATION_SUPERVISOR2',
  TASK: 'TASK',
  LEAVE_REQUEST: 'LEAVE_REQUEST',
  LEAVE_REQUEST_RESPONSE: 'LEAVE_REQUEST_RESPONSE',
  PAYROLL: 'PAYROLL',
  ACCEPTANCE_HANDOVER: 'ACCEPTANCE_HANDOVER',
  OVERTIME_PLAN: 'OVERTIME_PLAN',
  OVERTIME_PLAN_APPROVAL: 'OVERTIME_PLAN_APPROVAL',
  ATTENDANCE_REMINDER: 'ATTENDANCE_REMINDER',
  ORDER: 'ORDER',
  QUALITY_EVALUATION: 'QUALITY_EVALUATION',
  SUPPLY_REQUEST: 'SUPPLY_REQUEST',
  WAREHOUSE_RECEIPT: 'WAREHOUSE_RECEIPT',
  ATTENDANCE_CHANGED: 'ATTENDANCE_CHANGED',
  OVERTIME_PLAN_CHANGED: 'OVERTIME_PLAN_CHANGED',
  MEETING_CREATED: 'MEETING_CREATED',
  MEETING_UPDATED: 'MEETING_UPDATED',
  MEETING_CANCELLED: 'MEETING_CANCELLED',
  MEETING_REMINDER: 'MEETING_REMINDER',
  SUPPLY_ADJUSTMENT_CREATED: 'SUPPLY_ADJUSTMENT_CREATED',
  SUPPLY_ADJUSTMENT_APPROVED: 'SUPPLY_ADJUSTMENT_APPROVED',
  SUPPLY_ADJUSTMENT_REJECTED: 'SUPPLY_ADJUSTMENT_REJECTED',
  PRIVATE_FEEDBACK: 'PRIVATE_FEEDBACK',
  PURCHASE_REQUEST: 'PURCHASE_REQUEST',
  WORK_PLAN: 'WORK_PLAN',
  DAILY_WORK_REPORT: 'DAILY_WORK_REPORT',
  PROCESS_CREATED: 'PROCESS_CREATED',
  PROCESS_UPDATED: 'PROCESS_UPDATED',
} as const;

export type NotificationType = typeof NotificationType[keyof typeof NotificationType];

/**
 * Evaluation status constants
 * Tập trung tất cả evaluation statuses để tránh magic strings
 */
export const EvaluationStatus = {
  SELF_PENDING: 'SELF_PENDING',
  SUPERVISOR1_PENDING: 'SUPERVISOR1_PENDING',
  SUPERVISOR2_PENDING: 'SUPERVISOR2_PENDING',
  COMPLETED: 'COMPLETED',
} as const;

export type EvaluationStatus = typeof EvaluationStatus[keyof typeof EvaluationStatus];

/**
 * Leave request status constants
 */
export const LeaveRequestStatusConst = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
} as const;

export type LeaveRequestStatusConst = typeof LeaveRequestStatusConst[keyof typeof LeaveRequestStatusConst];

