"""Tool registry — curated list of ERP API tools for the agent."""

from typing import List

TOOLS: List[dict] = [
    # ─── Attendance ──────────────────────────────────────────────────────────
    {
        "name": "get_attendance_by_date",
        "description": "Xem danh sách chấm công theo khoảng thời gian",
        "method": "GET",
        "path": "/api/attendances/date-range",
        "path_params": [],
        "query_params": [
            {"name": "startDate", "type": "string", "required": True, "description": "Ngày bắt đầu (YYYY-MM-DD)"},
            {"name": "endDate", "type": "string", "required": True, "description": "Ngày kết thúc (YYYY-MM-DD)"},
        ],
        "body_params": [],
        "is_write": False,
        "is_export": False,
        "required_roles": [],
        "category": "attendance",
    },
    {
        "name": "export_attendance_excel",
        "description": "Xuất file Excel chấm công theo khoảng thời gian",
        "method": "GET",
        "path": "/api/attendances/export/excel",
        "path_params": [],
        "query_params": [
            {"name": "startDate", "type": "string", "required": False, "description": "Ngày bắt đầu (YYYY-MM-DD)"},
            {"name": "endDate", "type": "string", "required": False, "description": "Ngày kết thúc (YYYY-MM-DD)"},
        ],
        "body_params": [],
        "is_write": False,
        "is_export": True,
        "required_roles": [],
        "category": "attendance",
    },
    # ─── Leave Requests ──────────────────────────────────────────────────────
    {
        "name": "list_leave_requests",
        "description": "Xem danh sách đơn nghỉ phép",
        "method": "GET",
        "path": "/api/leave-requests",
        "path_params": [],
        "query_params": [
            {"name": "page", "type": "integer", "required": False, "description": "Số trang"},
            {"name": "limit", "type": "integer", "required": False, "description": "Số lượng mỗi trang"},
            {"name": "status", "type": "string", "required": False, "description": "Trạng thái: pending (chờ duyệt), approved (đã duyệt), rejected (từ chối)", "enum": ["pending", "approved", "rejected"]},
        ],
        "body_params": [],
        "is_write": False,
        "is_export": False,
        "required_roles": [],
        "category": "leave",
    },
    {
        "name": "create_leave_request",
        "description": "Tạo đơn xin nghỉ phép mới",
        "method": "POST",
        "path": "/api/leave-requests",
        "path_params": [],
        "query_params": [],
        "body_params": [
            {"name": "employeeId", "type": "string", "required": True, "description": "ID nhân viên (lấy từ field employeeId trong get_my_profile, KHÔNG phải field id)"},
            {"name": "leaveType", "type": "string", "required": True, "description": "Loại nghỉ phép (enum): ANNUAL (nghỉ phép năm), SICK (nghỉ ốm), PERSONAL (nghỉ việc riêng), MATERNITY (nghỉ thai sản), EMERGENCY (nghỉ khẩn cấp), COMPENSATORY (nghỉ bù)"},
            {"name": "startDate", "type": "string", "required": True, "description": "Ngày bắt đầu (YYYY-MM-DD)"},
            {"name": "endDate", "type": "string", "required": True, "description": "Ngày kết thúc (YYYY-MM-DD)"},
            {"name": "reason", "type": "string", "required": True, "description": "Lý do nghỉ phép"},
        ],
        "is_write": True,
        "is_export": False,
        "required_roles": [],
        "category": "leave",
    },
    {
        "name": "approve_leave_request",
        "description": "Duyệt đơn nghỉ phép",
        "method": "PATCH",
        "path": "/api/leave-requests/{id}/approve",
        "path_params": [{"name": "id", "type": "string", "required": True, "description": "ID đơn nghỉ phép"}],
        "query_params": [],
        "body_params": [
            {"name": "approvedBy", "type": "string", "required": True, "description": "ID người duyệt (lấy từ get_my_profile)"},
        ],
        "is_write": True,
        "is_export": False,
        "required_roles": ["ADMIN", "DEPARTMENT_HEAD", "TEAM_LEAD"],
        "category": "leave",
    },
    # ─── Customers ──────────────────────────────────────────────────────────
    {
        "name": "list_customers",
        "description": "Xem danh sách khách hàng. Dùng phanLoaiDiaLy='Quốc tế' cho KH quốc tế, 'Nội địa' cho KH nội địa",
        "method": "GET",
        "path": "/api/international-customers",
        "path_params": [],
        "query_params": [
            {"name": "page", "type": "integer", "required": False},
            {"name": "limit", "type": "integer", "required": False},
            {"name": "search", "type": "string", "required": False, "description": "Tìm theo tên/mã KH"},
            {"name": "phanLoaiDiaLy", "type": "string", "required": False, "description": "Phân loại: Quốc tế hoặc Nội địa", "enum": ["Quốc tế", "Nội địa"]},
        ],
        "body_params": [],
        "is_write": False,
        "is_export": False,
        "required_roles": [],
        "category": "customer",
    },
    {
        "name": "create_customer",
        "description": "Tạo khách hàng mới. Khách quốc tế cần quocGia, nội địa cần tinhThanh.",
        "method": "POST",
        "path": "/api/international-customers",
        "path_params": [],
        "query_params": [],
        "body_params": [
            {"name": "tenCongTy", "type": "string", "required": True, "description": "Tên công ty/khách hàng"},
            {"name": "nguoiLienHe", "type": "string", "required": True, "description": "Người liên hệ"},
            {"name": "loaiKhachHang", "type": "string", "required": True, "description": "Loại: Nhập khẩu/Xuất khẩu/Nội địa/Cả hai"},
            {"name": "quocGia", "type": "string", "required": False, "description": "Quốc gia (bắt buộc với khách quốc tế)"},
            {"name": "tinhThanh", "type": "string", "required": False, "description": "Tỉnh/Thành phố (bắt buộc với khách nội địa)"},
            {"name": "email", "type": "string", "required": False, "description": "Email liên hệ"},
            {"name": "soDienThoai", "type": "string", "required": False, "description": "Số điện thoại"},
            {"name": "diaChi", "type": "string", "required": False, "description": "Địa chỉ"},
            {"name": "sanPhamChinh", "type": "string", "required": False, "description": "Sản phẩm chính quan tâm"},
            {"name": "ghiChu", "type": "string", "required": False, "description": "Ghi chú"},
        ],
        "is_write": True,
        "is_export": False,
        "required_roles": ["ADMIN", "DEPARTMENT_HEAD"],
        "category": "customer",
    },
    # ─── Orders ─────────────────────────────────────────────────────────────
    {
        "name": "list_orders",
        "description": "Xem danh sách đơn hàng",
        "method": "GET",
        "path": "/api/orders",
        "path_params": [],
        "query_params": [
            {"name": "page", "type": "integer", "required": False, "description": "Số trang"},
            {"name": "limit", "type": "integer", "required": False, "description": "Số lượng mỗi trang"},
            {"name": "status", "type": "string", "required": False, "description": "Trạng thái đơn hàng", "enum": ["pending", "approved", "rejected", "completed", "cancelled"]},
        ],
        "body_params": [],
        "is_write": False,
        "is_export": False,
        "required_roles": [],
        "category": "order",
    },
    {
        "name": "get_order_detail",
        "description": "Xem chi tiết một đơn hàng",
        "method": "GET",
        "path": "/api/orders/{id}",
        "path_params": [{"name": "id", "type": "string", "required": True, "description": "ID đơn hàng"}],
        "query_params": [],
        "body_params": [],
        "is_write": False,
        "is_export": False,
        "required_roles": [],
        "category": "order",
    },
    {
        "name": "export_orders_excel",
        "description": "Xuất file Excel danh sách đơn hàng",
        "method": "GET",
        "path": "/api/orders/export/excel",
        "path_params": [],
        "query_params": [
            {"name": "startDate", "type": "string", "required": False, "description": "Ngày bắt đầu (YYYY-MM-DD)"},
            {"name": "endDate", "type": "string", "required": False, "description": "Ngày kết thúc (YYYY-MM-DD)"},
        ],
        "body_params": [],
        "is_write": False,
        "is_export": True,
        "required_roles": [],
        "category": "order",
    },
    {
        "name": "create_order_from_quotation",
        "description": "Tạo đơn hàng từ báo giá đã được chấp nhận. Cần quotationId; file đính kèm là tùy chọn và agent không gửi file qua tool này.",
        "method": "POST",
        "path": "/api/orders/from-quotation",
        "path_params": [],
        "query_params": [],
        "body_params": [
            {"name": "quotationId", "type": "string", "required": True, "description": "ID báo giá"},
        ],
        "is_write": True,
        "is_export": False,
        "required_roles": ["ADMIN", "DEPARTMENT_HEAD"],
        "category": "order",
    },
    # ─── Tasks ──────────────────────────────────────────────────────────────
    {
        "name": "list_my_tasks",
        "description": "Xem danh sách công việc của tôi",
        "method": "GET",
        "path": "/api/tasks/my-tasks",
        "path_params": [],
        "query_params": [
            {"name": "status", "type": "string", "required": False, "description": "Trạng thái: pending/in_progress/completed"},
        ],
        "body_params": [],
        "is_write": False,
        "is_export": False,
        "required_roles": [],
        "category": "task",
    },
    # ─── Employees ──────────────────────────────────────────────────────────
    {
        "name": "list_employees",
        "description": "Xem danh sách nhân viên. Có thể tìm theo tên, bộ phận, chức vụ.",
        "method": "GET",
        "path": "/api/employees",
        "path_params": [],
        "query_params": [
            {"name": "page", "type": "integer", "required": False, "description": "Số trang"},
            {"name": "limit", "type": "integer", "required": False, "description": "Số lượng mỗi trang (mặc định 10, tối đa 100)"},
            {"name": "search", "type": "string", "required": False, "description": "Tìm kiếm theo tên nhân viên, mã NV, email, chức vụ, hoặc tên bộ phận (ví dụ: 'kế toán', 'kinh doanh')"},
        ],
        "body_params": [],
        "is_write": False,
        "is_export": False,
        "required_roles": ["ADMIN", "DEPARTMENT_HEAD", "TEAM_LEAD"],
        "category": "employee",
    },
    {
        "name": "export_employees_excel",
        "description": "Xuất file Excel danh sách nhân viên",
        "method": "GET",
        "path": "/api/employees/export/excel",
        "path_params": [],
        "query_params": [],
        "body_params": [],
        "is_write": False,
        "is_export": True,
        "required_roles": ["ADMIN", "DEPARTMENT_HEAD", "TEAM_LEAD"],
        "category": "employee",
    },
    {
        "name": "get_my_profile",
        "description": "Lấy thông tin cá nhân (id, employeeId, mã NV, tên, phòng ban). Dùng employeeId cho các API tạo mới.",
        "method": "GET",
        "path": "/api/users/profile",
        "path_params": [],
        "query_params": [],
        "body_params": [],
        "is_write": False,
        "is_export": False,
        "required_roles": [],
        "category": "employee",
    },
    # ─── Notifications ──────────────────────────────────────────────────────
    {
        "name": "list_notifications",
        "description": "Xem danh sách thông báo",
        "method": "GET",
        "path": "/api/notifications",
        "path_params": [],
        "query_params": [
            {"name": "page", "type": "integer", "required": False, "description": "Số trang"},
            {"name": "limit", "type": "integer", "required": False, "description": "Số lượng mỗi trang"},
        ],
        "body_params": [],
        "is_write": False,
        "is_export": False,
        "required_roles": [],
        "category": "notification",
    },
    # ─── Suppliers ──────────────────────────────────────────────────────────
    {
        "name": "list_suppliers",
        "description": "Xem danh sách nhà cung cấp (nguyên vật liệu, thiết bị, bao bì). Dùng phanLoaiNCC='NVL' cho NCC nguyên vật liệu, 'Thiết bị' cho NCC thiết bị",
        "method": "GET",
        "path": "/api/suppliers",
        "path_params": [],
        "query_params": [
            {"name": "page", "type": "integer", "required": False},
            {"name": "limit", "type": "integer", "required": False},
            {"name": "search", "type": "string", "required": False, "description": "Tìm theo tên/mã NCC"},
            {"name": "phanLoaiNCC", "type": "string", "required": False, "description": "Phân loại: NVL hoặc Thiết bị"},
        ],
        "body_params": [],
        "is_write": False,
        "is_export": False,
        "required_roles": [],
        "category": "supplier",
    },
    # ─── Purchase Requests ──────────────────────────────────────────────────
    {
        "name": "list_purchase_requests",
        "description": "Xem danh sách yêu cầu mua hàng",
        "method": "GET",
        "path": "/api/purchase-requests",
        "path_params": [],
        "query_params": [
            {"name": "page", "type": "integer", "required": False, "description": "Số trang"},
            {"name": "limit", "type": "integer", "required": False, "description": "Số lượng mỗi trang"},
            {"name": "status", "type": "string", "required": False, "description": "Trạng thái: pending (chờ duyệt), approved (đã duyệt), rejected (từ chối)", "enum": ["pending", "approved", "rejected"]},
        ],
        "body_params": [],
        "is_write": False,
        "is_export": False,
        "required_roles": [],
        "category": "purchase",
    },
    {
        "name": "create_purchase_request",
        "description": "Tạo yêu cầu mua hàng mới. Cần gọi get_my_profile() trước để lấy employeeId, maNhanVien, tenNhanVien. Items cần ít nhất 1 sản phẩm với thông tin: phanLoai, tenHangHoa, soLuong, donViTinh, giaDuKien.",
        "method": "POST",
        "path": "/api/purchase-requests",
        "path_params": [],
        "query_params": [],
        "body_params": [
            {"name": "employeeId", "type": "string", "required": True, "description": "ID nhân viên (lấy từ field employeeId trong get_my_profile, KHÔNG phải field id)"},
            {"name": "maNhanVien", "type": "string", "required": True, "description": "Mã nhân viên (lấy từ get_my_profile)"},
            {"name": "tenNhanVien", "type": "string", "required": True, "description": "Tên nhân viên (lấy từ get_my_profile)"},
            {"name": "mucDichYeuCau", "type": "string", "required": True, "description": "Mục đích yêu cầu mua hàng"},
            {"name": "mucDoUuTien", "type": "string", "required": True, "description": "Mức độ ưu tiên: Cao/Trung bình/Thấp"},
            {"name": "ghiChu", "type": "string", "required": False, "description": "Ghi chú thêm"},
            {"name": "items", "type": "array", "required": True, "description": "Danh sách hàng hóa: [{phanLoai, tenHangHoa, soLuong, donViTinh, giaDuKien}]"},
        ],
        "is_write": True,
        "is_export": False,
        "required_roles": [],
        "category": "purchase",
    },
    # ─── Payroll ────────────────────────────────────────────────────────────
    {
        "name": "get_my_payroll",
        "description": "Xem bảng lương của tôi",
        "method": "GET",
        "path": "/api/payrolls",
        "path_params": [],
        "query_params": [
            {"name": "month", "type": "integer", "required": False, "description": "Tháng (1-12)"},
            {"name": "year", "type": "integer", "required": False, "description": "Năm"},
        ],
        "body_params": [],
        "is_write": False,
        "is_export": False,
        "required_roles": [],
        "category": "payroll",
    },
    # ─── Quotation Requests ─────────────────────────────────────────────────
    {
        "name": "list_quotation_requests",
        "description": "Xem danh sách yêu cầu báo giá",
        "method": "GET",
        "path": "/api/quotation-requests",
        "path_params": [],
        "query_params": [
            {"name": "page", "type": "integer", "required": False, "description": "Số trang"},
            {"name": "limit", "type": "integer", "required": False, "description": "Số lượng mỗi trang"},
            {"name": "status", "type": "string", "required": False, "description": "Trạng thái: pending (chờ xử lý), approved (đã duyệt), rejected (từ chối)", "enum": ["pending", "approved", "rejected"]},
        ],
        "body_params": [],
        "is_write": False,
        "is_export": False,
        "required_roles": [],
        "category": "quotation",
    },
    {
        "name": "list_products",
        "description": "Xem danh sách sản phẩm (trái cây sấy, rau củ sấy, v.v.). Dùng khi cần tìm productId cho báo giá hoặc kiểm tra tồn kho.",
        "method": "GET",
        "path": "/api/international-products",
        "path_params": [],
        "query_params": [
            {"name": "page", "type": "integer", "required": False, "description": "Số trang"},
            {"name": "limit", "type": "integer", "required": False, "description": "Số lượng mỗi trang"},
            {"name": "search", "type": "string", "required": False, "description": "Tìm kiếm theo tên/mã sản phẩm"},
        ],
        "body_params": [],
        "is_write": False,
        "is_export": False,
        "required_roles": [],
        "category": "product",
    },
    {
        "name": "create_quotation_request",
        "description": "Tạo yêu cầu báo giá mới cho khách hàng. LUÔN gọi list_customers trước để lấy customerId, list_products trước để lấy productId. Cần điền đầy đủ thông tin sản phẩm (productId, số lượng, đơn vị tính).",
        "method": "POST",
        "path": "/api/quotation-requests",
        "path_params": [],
        "query_params": [],
        "body_params": [
            {"name": "customerId", "type": "string", "required": True, "description": "ID khách hàng (lấy từ list_customers)"},
            {"name": "employeeId", "type": "string", "required": True, "description": "ID nhân viên (lấy từ field employeeId trong get_my_profile, KHÔNG phải field id)"},
            {"name": "items", "type": "array", "required": True, "description": "Danh sách sản phẩm: [{productId, soLuong, donViTinh, yeuCauSanPham?, quyDongGoi?, giaDoiThuBan?, giaBanGanNhat?}]"},
            {"name": "hinhThucVanChuyen", "type": "string", "required": False, "description": "Hình thức vận chuyển"},
            {"name": "hinhThucThanhToan", "type": "string", "required": False, "description": "Hình thức thanh toán"},
            {"name": "quocGia", "type": "string", "required": False, "description": "Quốc gia đích"},
            {"name": "cangDen", "type": "string", "required": False, "description": "Cảng đến"},
            {"name": "ghiChu", "type": "string", "required": False, "description": "Ghi chú thêm"},
        ],
        "is_write": True,
        "is_export": False,
        "required_roles": [],
        "category": "quotation",
    },
    {
        "name": "create_quotation",
        "description": "Tạo báo giá thật từ yêu cầu báo giá đã có. LUÔN dùng list_quotation_requests hoặc get kết quả vừa tạo để lấy quotationRequestId; maBaoGia có thể bỏ trống vì backend tự sinh. Items là thành phẩm đầu ra của báo giá, không phải items yêu cầu báo giá.",
        "method": "POST",
        "path": "/api/quotations",
        "path_params": [],
        "query_params": [],
        "body_params": [
            {"name": "maBaoGia", "type": "string", "required": False, "description": "Mã báo giá, bỏ trống để backend tự sinh"},
            {"name": "quotationRequestId", "type": "string", "required": True, "description": "ID yêu cầu báo giá"},
            {"name": "materialStandardId", "type": "string", "required": False, "description": "ID định mức nguyên vật liệu nếu có"},
            {"name": "tiLeThuHoi", "type": "number", "required": False, "description": "Tỉ lệ thu hồi"},
            {"name": "sanPhamDauRa", "type": "string", "required": False, "description": "Sản phẩm đầu ra"},
            {"name": "thanhPhamTonKho", "type": "number", "required": False, "description": "Thành phẩm tồn kho"},
            {"name": "tongThanhPhamCanSxThem", "type": "number", "required": False, "description": "Tổng thành phẩm cần sản xuất thêm"},
            {"name": "tongNguyenLieuCanSanXuat", "type": "number", "required": False, "description": "Tổng nguyên liệu cần sản xuất"},
            {"name": "nguyenLieuTonKho", "type": "number", "required": False, "description": "Nguyên liệu tồn kho"},
            {"name": "nguyenLieuCanNhapThem", "type": "number", "required": False, "description": "Nguyên liệu cần nhập thêm"},
            {"name": "tinhTrang", "type": "string", "required": False, "description": "Trạng thái báo giá", "enum": ["DRAFT", "SENT", "APPROVED", "REJECTED", "EXPIRED"]},
            {"name": "ghiChu", "type": "string", "required": False, "description": "Ghi chú"},
            {"name": "items", "type": "array", "required": False, "description": "Thành phẩm báo giá: [{tenThanhPham, tiLe, khoiLuongTuongUng?}]"},
        ],
        "is_write": True,
        "is_export": False,
        "required_roles": ["ADMIN", "DEPARTMENT_HEAD"],
        "category": "quotation",
    },
    # ─── Sản xuất & Chất lượng ─────────────────────────────────────────────
    {
        "name": "list_quality_evaluations",
        "description": "Xem đánh giá chất lượng thành phẩm sấy (màu, mùi, vị, độ giòn, tỉ lệ A/B/C)",
        "method": "GET",
        "path": "/api/quality-evaluations",
        "path_params": [],
        "query_params": [
            {"name": "page", "type": "integer", "required": False, "description": "Số trang"},
            {"name": "limit", "type": "integer", "required": False, "description": "Số lượng mỗi trang"},
        ],
        "body_params": [],
        "is_write": False,
        "is_export": False,
        "required_roles": [],
        "category": "production",
    },
    {
        "name": "list_finished_products",
        "description": "Xem thành phẩm đầu ra sau sấy (khối lượng loại A/B/C, vụn, phế phẩm)",
        "method": "GET",
        "path": "/api/finished-products",
        "path_params": [],
        "query_params": [
            {"name": "page", "type": "integer", "required": False, "description": "Số trang"},
            {"name": "limit", "type": "integer", "required": False, "description": "Số lượng mỗi trang"},
        ],
        "body_params": [],
        "is_write": False,
        "is_export": False,
        "required_roles": [],
        "category": "production",
    },
    {
        "name": "list_production_reports",
        "description": "Xem báo cáo sản lượng hàng ngày (số mẻ sấy, khối lượng NL/TP)",
        "method": "GET",
        "path": "/api/production-reports",
        "path_params": [],
        "query_params": [
            {"name": "page", "type": "integer", "required": False, "description": "Số trang"},
            {"name": "limit", "type": "integer", "required": False, "description": "Số lượng mỗi trang"},
        ],
        "body_params": [],
        "is_write": False,
        "is_export": False,
        "required_roles": [],
        "category": "production",
    },
    {
        "name": "list_material_evaluations",
        "description": "Xem đánh giá nguyên liệu đầu vào (mít tươi: độ chín, Brix, nhiệt độ ngâm)",
        "method": "GET",
        "path": "/api/material-evaluations",
        "path_params": [],
        "query_params": [
            {"name": "page", "type": "integer", "required": False, "description": "Số trang"},
            {"name": "limit", "type": "integer", "required": False, "description": "Số lượng mỗi trang"},
        ],
        "body_params": [],
        "is_write": False,
        "is_export": False,
        "required_roles": [],
        "category": "production",
    },
    # ─── Kho & Lô hàng ────────────────────────────────────────────────────
    {
        "name": "list_warehouses",
        "description": "Xem danh sách kho hàng",
        "method": "GET",
        "path": "/api/warehouses",
        "path_params": [],
        "query_params": [
            {"name": "page", "type": "integer", "required": False, "description": "Số trang"},
            {"name": "limit", "type": "integer", "required": False, "description": "Số lượng mỗi trang"},
        ],
        "body_params": [],
        "is_write": False,
        "is_export": False,
        "required_roles": [],
        "category": "warehouse",
    },
    {
        "name": "list_warehouse_receipts",
        "description": "Xem phiếu nhập kho",
        "method": "GET",
        "path": "/api/warehouse-receipts",
        "path_params": [],
        "query_params": [
            {"name": "page", "type": "integer", "required": False, "description": "Số trang"},
            {"name": "limit", "type": "integer", "required": False, "description": "Số lượng mỗi trang"},
        ],
        "body_params": [],
        "is_write": False,
        "is_export": False,
        "required_roles": [],
        "category": "warehouse",
    },
    {
        "name": "list_warehouse_issues",
        "description": "Xem phiếu xuất kho",
        "method": "GET",
        "path": "/api/warehouse-issues",
        "path_params": [],
        "query_params": [
            {"name": "page", "type": "integer", "required": False, "description": "Số trang"},
            {"name": "limit", "type": "integer", "required": False, "description": "Số lượng mỗi trang"},
        ],
        "body_params": [],
        "is_write": False,
        "is_export": False,
        "required_roles": [],
        "category": "warehouse",
    },
    {
        "name": "list_lots",
        "description": "Xem danh sách lô hàng",
        "method": "GET",
        "path": "/api/lots",
        "path_params": [],
        "query_params": [
            {"name": "page", "type": "integer", "required": False, "description": "Số trang"},
            {"name": "limit", "type": "integer", "required": False, "description": "Số lượng mỗi trang"},
        ],
        "body_params": [],
        "is_write": False,
        "is_export": False,
        "required_roles": [],
        "category": "warehouse",
    },
    # ─── Máy móc & Bảo trì ────────────────────────────────────────────────
    {
        "name": "list_machines",
        "description": "Xem danh sách máy móc/thiết bị",
        "method": "GET",
        "path": "/api/machines",
        "path_params": [],
        "query_params": [
            {"name": "page", "type": "integer", "required": False, "description": "Số trang"},
            {"name": "limit", "type": "integer", "required": False, "description": "Số lượng mỗi trang"},
        ],
        "body_params": [],
        "is_write": False,
        "is_export": False,
        "required_roles": [],
        "category": "maintenance",
    },
    {
        "name": "list_repair_requests",
        "description": "Xem yêu cầu sửa chữa",
        "method": "GET",
        "path": "/api/repair-requests",
        "path_params": [],
        "query_params": [
            {"name": "page", "type": "integer", "required": False, "description": "Số trang"},
            {"name": "limit", "type": "integer", "required": False, "description": "Số lượng mỗi trang"},
            {"name": "trangThai", "type": "string", "required": False, "description": "Trạng thái: Chờ xử lý/Đang sửa/Hoàn thành"},
        ],
        "body_params": [],
        "is_write": False,
        "is_export": False,
        "required_roles": [],
        "category": "maintenance",
    },
    {
        "name": "list_machine_activity_reports",
        "description": "Xem báo cáo hoạt động máy (thời gian chạy/dừng, hiệu suất)",
        "method": "GET",
        "path": "/api/machine-activity-reports",
        "path_params": [],
        "query_params": [
            {"name": "page", "type": "integer", "required": False, "description": "Số trang"},
            {"name": "limit", "type": "integer", "required": False, "description": "Số lượng mỗi trang"},
        ],
        "body_params": [],
        "is_write": False,
        "is_export": False,
        "required_roles": [],
        "category": "maintenance",
    },
    {
        "name": "list_machine_systems",
        "description": "Xem danh sách hệ thống máy",
        "method": "GET",
        "path": "/api/machine-systems",
        "path_params": [],
        "query_params": [
            {"name": "page", "type": "integer", "required": False, "description": "Số trang"},
            {"name": "limit", "type": "integer", "required": False, "description": "Số lượng mỗi trang"},
        ],
        "body_params": [],
        "is_write": False,
        "is_export": False,
        "required_roles": [],
        "category": "maintenance",
    },
    # ─── Tài chính ────────────────────────────────────────────────────────
    {
        "name": "list_invoices",
        "description": "Xem danh sách hóa đơn",
        "method": "GET",
        "path": "/api/invoices",
        "path_params": [],
        "query_params": [
            {"name": "page", "type": "integer", "required": False, "description": "Số trang"},
            {"name": "limit", "type": "integer", "required": False, "description": "Số lượng mỗi trang"},
            {"name": "search", "type": "string", "required": False, "description": "Tìm kiếm theo mã/tên"},
        ],
        "body_params": [],
        "is_write": False,
        "is_export": False,
        "required_roles": [],
        "category": "finance",
    },
    {
        "name": "list_debts",
        "description": "Xem danh sách công nợ",
        "method": "GET",
        "path": "/api/debts",
        "path_params": [],
        "query_params": [
            {"name": "page", "type": "integer", "required": False, "description": "Số trang"},
            {"name": "limit", "type": "integer", "required": False, "description": "Số lượng mỗi trang"},
        ],
        "body_params": [],
        "is_write": False,
        "is_export": False,
        "required_roles": ["ADMIN", "DEPARTMENT_HEAD"],
        "category": "finance",
    },
    {
        "name": "list_general_costs",
        "description": "Xem chi phí chung sản xuất (điện, nước, nhân công, khấu hao)",
        "method": "GET",
        "path": "/api/general-costs",
        "path_params": [],
        "query_params": [
            {"name": "page", "type": "integer", "required": False, "description": "Số trang"},
            {"name": "limit", "type": "integer", "required": False, "description": "Số lượng mỗi trang"},
        ],
        "body_params": [],
        "is_write": False,
        "is_export": False,
        "required_roles": ["ADMIN", "DEPARTMENT_HEAD"],
        "category": "finance",
    },
    # ─── Kế hoạch & Báo cáo ──────────────────────────────────────────────
    {
        "name": "list_work_plans",
        "description": "Xem kế hoạch công việc",
        "method": "GET",
        "path": "/api/work-plans",
        "path_params": [],
        "query_params": [
            {"name": "page", "type": "integer", "required": False, "description": "Số trang"},
            {"name": "limit", "type": "integer", "required": False, "description": "Số lượng mỗi trang"},
        ],
        "body_params": [],
        "is_write": False,
        "is_export": False,
        "required_roles": [],
        "category": "planning",
    },
    {
        "name": "list_daily_work_reports",
        "description": "Xem danh sách báo cáo công việc hàng ngày.",
        "method": "GET",
        "path": "/api/daily-work-reports",
        "path_params": [],
        "query_params": [
            {"name": "page", "type": "integer", "required": False, "description": "Số trang"},
            {"name": "limit", "type": "integer", "required": False, "description": "Số lượng mỗi trang"},
            {"name": "employeeId", "type": "string", "required": False, "description": "Lọc theo nhân viên"},
        ],
        "body_params": [],
        "is_write": False,
        "is_export": False,
        "required_roles": [],
        "category": "report",
    },
    {
        "name": "list_overtime_plans",
        "description": "Xem kế hoạch tăng ca",
        "method": "GET",
        "path": "/api/overtime-plans",
        "path_params": [],
        "query_params": [
            {"name": "page", "type": "integer", "required": False, "description": "Số trang"},
            {"name": "limit", "type": "integer", "required": False, "description": "Số lượng mỗi trang"},
        ],
        "body_params": [],
        "is_write": False,
        "is_export": False,
        "required_roles": [],
        "category": "planning",
    },
    # ─── Báo giá & Đơn hàng ──────────────────────────────────────────────
    {
        "name": "list_quotations",
        "description": "Xem danh sách báo giá",
        "method": "GET",
        "path": "/api/quotations",
        "path_params": [],
        "query_params": [
            {"name": "page", "type": "integer", "required": False, "description": "Số trang"},
            {"name": "limit", "type": "integer", "required": False, "description": "Số lượng mỗi trang"},
        ],
        "body_params": [],
        "is_write": False,
        "is_export": False,
        "required_roles": [],
        "category": "quotation",
    },
    # ─── Quy trình & Định mức ─────────────────────────────────────────────
    {
        "name": "list_material_standards",
        "description": "Xem định mức nguyên vật liệu",
        "method": "GET",
        "path": "/api/material-standards",
        "path_params": [],
        "query_params": [
            {"name": "page", "type": "integer", "required": False, "description": "Số trang"},
            {"name": "limit", "type": "integer", "required": False, "description": "Số lượng mỗi trang"},
        ],
        "body_params": [],
        "is_write": False,
        "is_export": False,
        "required_roles": [],
        "category": "production",
    },
    {
        "name": "list_system_operations",
        "description": "Xem vận hành hệ thống sấy (nhiệt độ, áp suất các giai đoạn)",
        "method": "GET",
        "path": "/api/system-operations",
        "path_params": [],
        "query_params": [
            {"name": "page", "type": "integer", "required": False, "description": "Số trang"},
            {"name": "limit", "type": "integer", "required": False, "description": "Số lượng mỗi trang"},
        ],
        "body_params": [],
        "is_write": False,
        "is_export": False,
        "required_roles": [],
        "category": "production",
    },
    {
        "name": "list_departments",
        "description": "Xem danh sách phòng ban",
        "method": "GET",
        "path": "/api/departments",
        "path_params": [],
        "query_params": [
            {"name": "page", "type": "integer", "required": False, "description": "Số trang"},
            {"name": "limit", "type": "integer", "required": False, "description": "Số lượng mỗi trang"},
        ],
        "body_params": [],
        "is_write": False,
        "is_export": False,
        "required_roles": [],
        "category": "hr",
    },
    {
        "name": "list_customer_feedbacks",
        "description": "Xem phản hồi/khiếu nại từ khách hàng",
        "method": "GET",
        "path": "/api/customer-feedbacks",
        "path_params": [],
        "query_params": [
            {"name": "page", "type": "integer", "required": False, "description": "Số trang"},
            {"name": "limit", "type": "integer", "required": False, "description": "Số lượng mỗi trang"},
        ],
        "body_params": [],
        "is_write": False,
        "is_export": False,
        "required_roles": [],
        "category": "feedback",
    },
    {
        "name": "list_work_shifts",
        "description": "Xem ca làm việc",
        "method": "GET",
        "path": "/api/work-shifts",
        "path_params": [],
        "query_params": [
            {"name": "page", "type": "integer", "required": False, "description": "Số trang"},
            {"name": "limit", "type": "integer", "required": False, "description": "Số lượng mỗi trang"},
        ],
        "body_params": [],
        "is_write": False,
        "is_export": False,
        "required_roles": [],
        "category": "hr",
    },
    # ─── Write Actions (Tạo mới) ──────────────────────────────────────────
    {
        "name": "create_task",
        "description": "Giao nhiệm vụ cho nhân viên",
        "method": "POST",
        "path": "/api/tasks",
        "path_params": [],
        "query_params": [],
        "body_params": [
            {"name": "nguoiNhan", "type": "array", "required": True, "description": "Danh sách employee ID (cuid format, VD: cmp23w0ra00eco18l...) của người nhận. Gọi list_employees trước, lấy field 'id' từ kết quả."},
            {"name": "noiDung", "type": "string", "required": True, "description": "Nội dung nhiệm vụ"},
            {"name": "thoiHanHoanThanh", "type": "string", "required": True, "description": "Thời hạn hoàn thành (YYYY-MM-DD)"},
            {"name": "mucDoUuTien", "type": "string", "required": True, "description": "Mức độ ưu tiên: KHAN_CAP/CAO/TRUNG_BINH/THAP"},
            {"name": "ghiChu", "type": "string", "required": False, "description": "Ghi chú thêm"},
        ],
        "is_write": True,
        "is_export": False,
        "required_roles": [],
        "category": "task",
    },
    {
        "name": "create_product",
        "description": "Tạo sản phẩm mới",
        "method": "POST",
        "path": "/api/international-products",
        "path_params": [],
        "query_params": [],
        "body_params": [
            {"name": "tenSanPham", "type": "string", "required": True, "description": "Tên sản phẩm"},
            {"name": "moTaSanPham", "type": "string", "required": False, "description": "Mô tả sản phẩm"},
            {"name": "loaiSanPham", "type": "string", "required": False, "description": "Loại sản phẩm (VD: Trái cây sấy, Rau củ sấy)"},
            {"name": "donViTinh", "type": "string", "required": False, "description": "Đơn vị tính (kg, thùng, gói...)"},
        ],
        "is_write": True,
        "is_export": False,
        "required_roles": ["ADMIN", "DEPARTMENT_HEAD"],
        "category": "product",
    },
    {
        "name": "create_supplier",
        "description": "Tạo nhà cung cấp mới",
        "method": "POST",
        "path": "/api/suppliers",
        "path_params": [],
        "query_params": [],
        "body_params": [
            {"name": "maNhaCungCap", "type": "string", "required": True, "description": "Mã nhà cung cấp (VD: NCC-001)"},
            {"name": "tenNhaCungCap", "type": "string", "required": True, "description": "Tên nhà cung cấp"},
            {"name": "loaiCungCap", "type": "string", "required": True, "description": "Loại cung cấp (Nguyên liệu/Bao bì/Thiết bị)"},
            {"name": "quocGia", "type": "string", "required": True, "description": "Quốc gia"},
            {"name": "nguoiLienHe", "type": "string", "required": True, "description": "Người liên hệ"},
            {"name": "soDienThoai", "type": "string", "required": True, "description": "Số điện thoại"},
            {"name": "emailLienHe", "type": "string", "required": True, "description": "Email liên hệ"},
            {"name": "diaChi", "type": "string", "required": True, "description": "Địa chỉ"},
            {"name": "loaiHinh", "type": "string", "required": True, "description": "Loại hình (Cá nhân/Doanh nghiệp)"},
            {"name": "employeeId", "type": "string", "required": True, "description": "ID nhân viên phụ trách (lấy từ get_my_profile)"},
            {"name": "website", "type": "string", "required": False, "description": "Website"},
            {"name": "khaNang", "type": "string", "required": False, "description": "Khả năng cung cấp"},
        ],
        "is_write": True,
        "is_export": False,
        "required_roles": ["ADMIN", "DEPARTMENT_HEAD"],
        "category": "supplier",
    },
    {
        "name": "list_supply_requests",
        "description": "Xem danh sách yêu cầu cung ứng vật tư/nguyên liệu",
        "method": "GET",
        "path": "/api/supply-requests",
        "path_params": [],
        "query_params": [
            {"name": "page", "type": "integer", "required": False, "description": "Trang"},
            {"name": "limit", "type": "integer", "required": False, "description": "Số lượng/trang"},
            {"name": "search", "type": "string", "required": False, "description": "Tìm theo mã hoặc tên nhân viên"},
            {"name": "status", "type": "string", "required": False, "description": "Trạng thái: pending (chờ xử lý), approved (đã duyệt), rejected (từ chối)", "enum": ["pending", "approved", "rejected"]},
        ],
        "body_params": [],
        "is_write": False,
        "is_export": False,
        "required_roles": [],
        "category": "supply",
    },
    {
        "name": "create_supply_request",
        "description": "Tạo yêu cầu cung ứng vật tư/nguyên liệu",
        "method": "POST",
        "path": "/api/supply-requests",
        "path_params": [],
        "query_params": [],
        "body_params": [
            {"name": "employeeId", "type": "string", "required": True, "description": "ID nhân viên (lấy từ field employeeId trong get_my_profile, KHÔNG phải field id)"},
            {"name": "maNhanVien", "type": "string", "required": True, "description": "Mã nhân viên (lấy từ get_my_profile)"},
            {"name": "tenNhanVien", "type": "string", "required": True, "description": "Tên nhân viên (lấy từ get_my_profile)"},
            {"name": "boPhan", "type": "string", "required": True, "description": "Bộ phận/phòng ban"},
            {"name": "mucDichYeuCau", "type": "string", "required": True, "description": "Mục đích yêu cầu cung ứng"},
            {"name": "mucDoUuTien", "type": "string", "required": True, "description": "Mức độ ưu tiên: Cao/Trung bình/Thấp"},
            {"name": "items", "type": "array", "required": True, "description": "Danh sách vật tư: [{phanLoai, tenGoi, soLuong, donViTinh}]"},
            {"name": "ghiChu", "type": "string", "required": False, "description": "Ghi chú thêm"},
        ],
        "is_write": True,
        "is_export": False,
        "required_roles": [],
        "category": "supply",
    },
    {
        "name": "create_daily_work_report",
        "description": "Tạo báo cáo công việc hàng ngày",
        "method": "POST",
        "path": "/api/daily-work-reports",
        "path_params": [],
        "query_params": [],
        "body_params": [
            {"name": "employeeId", "type": "string", "required": True, "description": "ID nhân viên (lấy từ field employeeId trong get_my_profile, KHÔNG phải field id)"},
            {"name": "reportDate", "type": "string", "required": True, "description": "Ngày báo cáo (YYYY-MM-DD)"},
            {"name": "workDescription", "type": "string", "required": True, "description": "Mô tả công việc đã làm"},
            {"name": "achievements", "type": "string", "required": False, "description": "Kết quả đạt được"},
            {"name": "challenges", "type": "string", "required": False, "description": "Khó khăn gặp phải"},
            {"name": "planForNextDay", "type": "string", "required": False, "description": "Kế hoạch ngày tiếp theo"},
            {"name": "workHours", "type": "number", "required": False, "description": "Số giờ làm việc"},
        ],
        "is_write": True,
        "is_export": False,
        "required_roles": [],
        "category": "report",
    },
    {
        "name": "create_customer_feedback",
        "description": "Tạo phản hồi/khiếu nại từ khách hàng",
        "method": "POST",
        "path": "/api/customer-feedbacks",
        "path_params": [],
        "query_params": [],
        "body_params": [
            {"name": "customerId", "type": "string", "required": True, "description": "ID khách hàng (lấy từ list_customers)"},
            {"name": "loaiPhanHoi", "type": "string", "required": True, "description": "Loại phản hồi: Khiếu nại/Góp ý/Yêu cầu hỗ trợ/Khen ngợi"},
            {"name": "mucDoNghiemTrong", "type": "string", "required": True, "description": "Mức độ: Cao/Trung bình/Thấp"},
            {"name": "noiDungPhanHoi", "type": "string", "required": True, "description": "Nội dung phản hồi chi tiết"},
            {"name": "sanPhamLienQuan", "type": "string", "required": False, "description": "Sản phẩm liên quan"},
            {"name": "donHangLienQuan", "type": "string", "required": False, "description": "Đơn hàng liên quan"},
            {"name": "ghiChu", "type": "string", "required": False, "description": "Ghi chú thêm"},
        ],
        "is_write": True,
        "is_export": False,
        "required_roles": [],
        "category": "feedback",
    },
    {
        "name": "create_repair_request",
        "description": "Tạo yêu cầu sửa chữa máy móc/thiết bị.",
        "method": "POST",
        "path": "/api/repair-requests",
        "path_params": [],
        "query_params": [],
        "body_params": [
            {"name": "ngayThang", "type": "string", "required": True, "description": "Ngày tạo yêu cầu (YYYY-MM-DD)"},
            {"name": "maYeuCau", "type": "string", "required": True, "description": "Mã yêu cầu sửa chữa (VD: SC-001)"},
            {"name": "tenHeThong", "type": "string", "required": True, "description": "Tên hệ thống/máy cần sửa"},
            {"name": "tinhTrangThietBi", "type": "string", "required": True, "description": "Tình trạng thiết bị hiện tại"},
            {"name": "loaiLoi", "type": "string", "required": True, "description": "Loại lỗi: Cơ khí/Điện/Điện tử/Phần mềm/Khác"},
            {"name": "mucDoUuTien", "type": "string", "required": True, "description": "Mức độ ưu tiên: Khẩn cấp/Cao/Trung bình/Thấp"},
            {"name": "noiDungLoi", "type": "string", "required": True, "description": "Mô tả chi tiết lỗi/hư hỏng"},
            {"name": "ghiChu", "type": "string", "required": False, "description": "Ghi chú thêm"},
        ],
        "is_write": True,
        "is_export": False,
        "required_roles": [],
        "category": "maintenance",
    },
    # ─── Quy trình & Đánh giá ─────────────────────────────────────────────
    {
        "name": "list_processes",
        "description": "Xem quy trình sản xuất",
        "method": "GET",
        "path": "/api/processes",
        "path_params": [],
        "query_params": [
            {"name": "page", "type": "integer", "required": False, "description": "Số trang"},
            {"name": "limit", "type": "integer", "required": False, "description": "Số lượng mỗi trang"},
        ],
        "body_params": [],
        "is_write": False,
        "is_export": False,
        "required_roles": [],
        "category": "production",
    },
    {
        "name": "create_process",
        "description": "Tạo quy trình mới. Dùng khi user muốn tạo quy trình từ file đã upload hoặc nhập tay. Gọi get_my_profile để lấy msnv và tenNhanVien trước.",
        "method": "POST",
        "path": "/api/processes",
        "path_params": [],
        "query_params": [],
        "body_params": [
            {"name": "msnv", "type": "string", "required": True, "description": "Mã số nhân viên người tạo (lấy từ get_my_profile)"},
            {"name": "tenNhanVien", "type": "string", "required": True, "description": "Tên nhân viên người tạo (lấy từ get_my_profile)"},
            {"name": "tenQuyTrinh", "type": "string", "required": True, "description": "Tên quy trình"},
            {"name": "loaiQuyTrinh", "type": "string", "required": True, "description": "Loại quy trình (VD: Quy trình sản xuất, Quy trình kiểm soát)"},
            {"name": "files", "type": "array", "required": False, "description": "Danh sách file đính kèm (URLs)"},
        ],
        "is_write": True,
        "is_export": False,
        "required_roles": ["ADMIN", "DEPARTMENT_HEAD", "TEAM_LEAD"],
        "category": "production",
    },
    {
        "name": "create_flowchart",
        "description": "Tạo lưu đồ cho quy trình. Dùng SAU khi tạo quy trình bằng create_process. Trích xuất các phân đoạn từ file và truyền vào đây. VÍ DỤ: sections=[{phanDoan:'1', tenPhanDoan:'Tiếp nhận hồ sơ', noiDungCongViec:'Tiếp nhận hồ sơ từ nhân viên mới'}, {phanDoan:'2', tenPhanDoan:'Kiểm tra', noiDungCongViec:'Kiểm tra tính đầy đủ'}]",
        "method": "POST",
        "path": "/api/processes/{processId}/flowchart",
        "path_params": [
            {"name": "processId", "type": "string", "required": True, "description": "ID quy trình (lấy từ kết quả create_process, field 'id')"},
        ],
        "query_params": [],
        "body_params": [
            {"name": "sections", "type": "array", "required": True, "description": "Mảng JSON các phân đoạn. Mỗi phần tử: {phanDoan: string, tenPhanDoan: string, noiDungCongViec: string, costs?: [{loaiChiPhi: string, tenChiPhi: string, donVi: string}]}. VD: [{phanDoan:'1', tenPhanDoan:'Tiếp nhận', noiDungCongViec:'Tiếp nhận hồ sơ'}]"},
        ],
        "is_write": True,
        "is_export": False,
        "required_roles": ["ADMIN", "DEPARTMENT_HEAD", "TEAM_LEAD"],
        "category": "production",
    },
    {
        "name": "list_production_processes",
        "description": "Xem quy trình sản xuất đang chạy (lô SX, giai đoạn, tiến độ)",
        "method": "GET",
        "path": "/api/production-processes",
        "path_params": [],
        "query_params": [
            {"name": "page", "type": "integer", "required": False, "description": "Số trang"},
            {"name": "limit", "type": "integer", "required": False, "description": "Số lượng mỗi trang"},
        ],
        "body_params": [],
        "is_write": False,
        "is_export": False,
        "required_roles": [],
        "category": "production",
    },
    {
        "name": "list_employee_evaluations",
        "description": "Xem đánh giá nhân viên (KPI, điểm, nhận xét)",
        "method": "GET",
        "path": "/api/employee-evaluations",
        "path_params": [],
        "query_params": [
            {"name": "page", "type": "integer", "required": False, "description": "Số trang"},
            {"name": "limit", "type": "integer", "required": False, "description": "Số lượng mỗi trang"},
        ],
        "body_params": [],
        "is_write": False,
        "is_export": False,
        "required_roles": ["ADMIN", "DEPARTMENT_HEAD"],
        "category": "hr",
    },
    {
        "name": "list_quotation_calculators",
        "description": "Xem tính giá/chi phí sản xuất",
        "method": "GET",
        "path": "/api/quotation-calculators",
        "path_params": [],
        "query_params": [
            {"name": "page", "type": "integer", "required": False, "description": "Số trang"},
            {"name": "limit", "type": "integer", "required": False, "description": "Số lượng mỗi trang"},
        ],
        "body_params": [],
        "is_write": False,
        "is_export": False,
        "required_roles": ["ADMIN", "DEPARTMENT_HEAD"],
        "category": "finance",
    },
    {
        "name": "upsert_quotation_calculator",
        "description": "Tạo hoặc cập nhật bảng tính giá cho yêu cầu báo giá. Dùng khi đã có quotationRequestId và dữ liệu products/generalCosts/exportCosts từ file hoặc trao đổi.",
        "method": "POST",
        "path": "/api/quotation-calculators",
        "path_params": [],
        "query_params": [],
        "body_params": [
            {"name": "quotationRequestId", "type": "string", "required": True, "description": "ID yêu cầu báo giá"},
            {"name": "maYeuCauBaoGia", "type": "string", "required": True, "description": "Mã yêu cầu báo giá"},
            {"name": "phanTramThue", "type": "number", "required": False, "description": "Phần trăm thuế"},
            {"name": "phanTramQuy", "type": "number", "required": False, "description": "Phần trăm quỹ"},
            {"name": "products", "type": "array", "required": True, "description": "Danh sách sản phẩm tính giá. Mỗi dòng cần tối thiểu {quotationRequestItemId, productId, tenSanPham, soLuong, donViTinh, maBaoGia}; có thể thêm materialStandardId, giaHoaVon, loiNhuanCongThem, thoiGianChoPhepToiDa, byProducts."},
            {"name": "generalCosts", "type": "array", "required": False, "description": "Chi phí chung: [{costId, maChiPhi, tenChiPhi, donViTinh?, keHoach, thucTe}]"},
            {"name": "exportCosts", "type": "array", "required": False, "description": "Chi phí xuất khẩu: [{costId, maChiPhi, tenChiPhi, donViTinh?, keHoach, thucTe}]"},
            {"name": "generalCostGroups", "type": "array", "required": False, "description": "Nhóm chi phí chung nếu có"},
        ],
        "is_write": True,
        "is_export": False,
        "required_roles": [],
        "category": "quotation",
    },
    {
        "name": "create_quotation_from_calculator",
        "description": "Tạo báo giá từ bảng tính giá đã lưu cho một yêu cầu báo giá.",
        "method": "POST",
        "path": "/api/quotation-calculators/quotation-request/{quotationRequestId}/create-quotation",
        "path_params": [
            {"name": "quotationRequestId", "type": "string", "required": True, "description": "ID yêu cầu báo giá"},
        ],
        "query_params": [],
        "body_params": [
            {"name": "hieuLucBaoGia", "type": "integer", "required": False, "description": "Hiệu lực báo giá theo ngày"},
            {"name": "tinhTrang", "type": "string", "required": False, "description": "Trạng thái báo giá"},
            {"name": "ghiChu", "type": "string", "required": False, "description": "Ghi chú"},
            {"name": "employeeId", "type": "string", "required": False, "description": "ID nhân viên"},
            {"name": "tenNhanVien", "type": "string", "required": False, "description": "Tên nhân viên"},
        ],
        "is_write": True,
        "is_export": False,
        "required_roles": [],
        "category": "quotation",
    },
    {
        "name": "list_export_costs",
        "description": "Xem chi phí xuất khẩu (vận chuyển, bảo hiểm, thuế)",
        "method": "GET",
        "path": "/api/export-costs",
        "path_params": [],
        "query_params": [
            {"name": "page", "type": "integer", "required": False, "description": "Số trang"},
            {"name": "limit", "type": "integer", "required": False, "description": "Số lượng mỗi trang"},
        ],
        "body_params": [],
        "is_write": False,
        "is_export": False,
        "required_roles": ["ADMIN", "DEPARTMENT_HEAD"],
        "category": "finance",
    },
    {
        "name": "list_tax_reports",
        "description": "Xem báo cáo thuế",
        "method": "GET",
        "path": "/api/tax-reports",
        "path_params": [],
        "query_params": [
            {"name": "page", "type": "integer", "required": False, "description": "Số trang"},
            {"name": "limit", "type": "integer", "required": False, "description": "Số lượng mỗi trang"},
        ],
        "body_params": [],
        "is_write": False,
        "is_export": False,
        "required_roles": ["ADMIN"],
        "category": "finance",
    },
    {
        "name": "list_lot_products",
        "description": "Xem sản phẩm trong lô hàng",
        "method": "GET",
        "path": "/api/lot-products",
        "path_params": [],
        "query_params": [
            {"name": "page", "type": "integer", "required": False, "description": "Số trang"},
            {"name": "limit", "type": "integer", "required": False, "description": "Số lượng mỗi trang"},
        ],
        "body_params": [],
        "is_write": False,
        "is_export": False,
        "required_roles": [],
        "category": "warehouse",
    },
    {
        "name": "list_acceptance_handovers",
        "description": "Xem biên bản nghiệm thu bàn giao",
        "method": "GET",
        "path": "/api/acceptance-handovers",
        "path_params": [],
        "query_params": [
            {"name": "page", "type": "integer", "required": False, "description": "Số trang"},
            {"name": "limit", "type": "integer", "required": False, "description": "Số lượng mỗi trang"},
        ],
        "body_params": [],
        "is_write": False,
        "is_export": False,
        "required_roles": [],
        "category": "warehouse",
    },
    {
        "name": "list_internal_inspections",
        "description": "Xem kiểm tra nội bộ",
        "method": "GET",
        "path": "/api/internal-inspections",
        "path_params": [],
        "query_params": [
            {"name": "page", "type": "integer", "required": False, "description": "Số trang"},
            {"name": "limit", "type": "integer", "required": False, "description": "Số lượng mỗi trang"},
        ],
        "body_params": [],
        "is_write": False,
        "is_export": False,
        "required_roles": ["ADMIN", "DEPARTMENT_HEAD"],
        "category": "production",
    },
    {
        "name": "list_material_evaluation_criteria",
        "description": "Xem tiêu chí đánh giá nguyên vật liệu",
        "method": "GET",
        "path": "/api/material-evaluation-criteria",
        "path_params": [],
        "query_params": [
            {"name": "page", "type": "integer", "required": False, "description": "Số trang"},
            {"name": "limit", "type": "integer", "required": False, "description": "Số lượng mỗi trang"},
        ],
        "body_params": [],
        "is_write": False,
        "is_export": False,
        "required_roles": [],
        "category": "production",
    },
    {
        "name": "list_private_feedbacks",
        "description": "Xem phản hồi nội bộ giữa nhân viên",
        "method": "GET",
        "path": "/api/private-feedbacks",
        "path_params": [],
        "query_params": [
            {"name": "page", "type": "integer", "required": False, "description": "Số trang"},
            {"name": "limit", "type": "integer", "required": False, "description": "Số lượng mỗi trang"},
        ],
        "body_params": [],
        "is_write": False,
        "is_export": False,
        "required_roles": [],
        "category": "feedback",
    },
    # ─── Documents ─────────────────────────────────────────────────────────────
    # ─── Knowledge Base (RAG) ──────────────────────────────────────────────
    {
        "name": "search_knowledge",
        "description": "Tìm hướng dẫn, quy trình, SOP trong knowledge base",
        "method": "INTERNAL",
        "path": "",
        "path_params": [],
        "query_params": [
            {"name": "query", "type": "string", "required": True, "description": "Câu hỏi cần tìm trong knowledge base"},
        ],
        "body_params": [],
        "is_write": False,
        "is_export": False,
        "is_internal": True,
        "required_roles": [],
        "category": "knowledge",
    },
]


# ─── Department → Category Access Mapping ──────────────────────────────────
# Categories accessible per department. Empty list = accessible to ALL departments.
DEPARTMENT_CATEGORY_ACCESS: dict[str, list[str]] = {
    "DEPT_BUSINESS": ["customer", "quotation", "order", "product", "feedback"],
    "DEPT_PURCHASING": ["supplier", "purchase"],
    "DEPT_QUALITY": ["production"],
    "DEPT_PRODUCTION": ["production", "warehouse"],
    "DEPT_TECHNICAL": ["maintenance"],
    "DEPT_ACCOUNTING": ["finance"],
    "DEPT_GENERAL": [],
}

# Categories accessible to ALL departments (common/shared functionality)
_COMMON_CATEGORIES: set[str] = {
    "attendance", "leave", "task", "employee", "notification",
    "knowledge", "report", "planning", "hr", "supply", "payroll",
    "document",
}


# ─── Helper Functions ───────────────────────────────────────────────────────

def get_tools_for_role(role: str) -> List[dict]:
    """Filter tools theo role của user. Trả về tools mà user có quyền dùng."""
    role_upper = role.upper() if role else ""
    return [
        t for t in TOOLS
        if not t["required_roles"] or role_upper in t["required_roles"]
    ]


def get_tools_for_department(tools: List[dict], department: str, role: str, secondary_departments: List[str] = None) -> List[dict]:
    """Filter tools theo department của user.

    - ADMIN: bypass, trả về tất cả tools
    - Other roles: chỉ trả về tools thuộc common categories + categories của primary + secondary departments
    """
    if not department or role.upper() == "ADMIN":
        return tools

    dept_categories = set(DEPARTMENT_CATEGORY_ACCESS.get(department, []))
    for sec_dept in (secondary_departments or []):
        dept_categories.update(DEPARTMENT_CATEGORY_ACCESS.get(sec_dept, []))

    allowed = _COMMON_CATEGORIES | dept_categories

    return [t for t in tools if t.get("category") in allowed]


def get_tool_by_name(name: str) -> dict | None:
    """Tìm tool theo tên."""
    for t in TOOLS:
        if t["name"] == name:
            return t
    return None


def to_openai_tools(tools: List[dict]) -> List[dict]:
    """Convert registry tools → OpenAI function calling format.
    Note: all types are sent as string to avoid validation errors
    (LLM often returns "100" instead of 100). _coerce_params handles conversion.
    Skips descriptions for obvious params (page, limit, startDate, endDate) to save tokens.
    """
    # Params whose purpose is obvious from the name — skip description
    _SKIP_DESC = {"page", "limit", "startDate", "endDate"}

    result = []
    for t in tools:
        properties = {}
        required = []

        for p in t.get("path_params", []) + t.get("query_params", []) + t.get("body_params", []):
            prop: dict = {"type": "string"}
            # Only include description for non-obvious params
            if p["name"] not in _SKIP_DESC:
                prop["description"] = p["description"]
            if p.get("enum"):
                prop["enum"] = p["enum"]
            properties[p["name"]] = prop
            if p.get("required"):
                required.append(p["name"])

        result.append({
            "type": "function",
            "function": {
                "name": t["name"],
                "description": t["description"],
                "parameters": {
                    "type": "object",
                    "properties": properties,
                    "required": required,
                },
            },
        })
    return result


# Keep backward-compatible alias
to_groq_tools = to_openai_tools
