// AUTO-GENERATED from frontend/src/constants/warehouseLayouts.ts — DO NOT EDIT BY HAND
// Baseline lots (one per zone) + physical slots (one per pallet cell) for the
// 6 warehouses with CAD floor plans. Consumed by warehouseLayoutSyncService.

export interface LayoutZone {
  zone: string;
  tenLo: string;
}

export interface LayoutSlotRef {
  zone: string;
  code: string;
}

export interface WarehouseBaseline {
  maKho: string;
  tenKho: string;
  zones: LayoutZone[];
  slots: LayoutSlotRef[];
}

const khotp: WarehouseBaseline = {
  maKho: 'KHOTP',
  tenKho: 'Kho thành phẩm sấy',
  zones: [
    { zone: 'LO1', tenLo: 'LÔ 1' },
    { zone: 'LO2', tenLo: 'LÔ 2' },
    { zone: 'LO3', tenLo: 'LÔ 3' },
    { zone: 'LO4', tenLo: 'LÔ 4' },
    { zone: 'LO5', tenLo: 'LÔ 5' },
    { zone: 'LO6', tenLo: 'LÔ 6' },
    { zone: 'LO7', tenLo: 'LÔ 7' },
    { zone: 'LO8', tenLo: 'LÔ 8' },
    { zone: 'LO9', tenLo: 'LÔ 9' },
    { zone: 'LO10', tenLo: 'LÔ 10' },
    { zone: 'LO11', tenLo: 'LÔ 11' },
  ],
  slots: [
    { zone: 'LO1', code: 'K1.1' },
    { zone: 'LO1', code: 'K1.2' },
    { zone: 'LO1', code: 'K1.3' },
    { zone: 'LO1', code: 'K1.4' },
    { zone: 'LO1', code: 'K1.5' },
    { zone: 'LO1', code: 'K1.6' },
    { zone: 'LO1', code: 'K1.7' },
    { zone: 'LO1', code: 'K1.8' },
    { zone: 'LO1', code: 'K1.9' },
    { zone: 'LO1', code: 'K1.10' },
    { zone: 'LO1', code: 'K1.11' },
    { zone: 'LO1', code: 'K1.12' },
    { zone: 'LO10', code: 'K10.1' },
    { zone: 'LO10', code: 'K10.2' },
    { zone: 'LO10', code: 'K10.3' },
    { zone: 'LO10', code: 'K10.4' },
    { zone: 'LO10', code: 'K10.5' },
    { zone: 'LO10', code: 'K10.6' },
    { zone: 'LO10', code: 'K10.7' },
    { zone: 'LO10', code: 'K10.8' },
    { zone: 'LO11', code: 'K11.1' },
    { zone: 'LO11', code: 'K11.2' },
    { zone: 'LO11', code: 'K11.3' },
    { zone: 'LO11', code: 'K11.4' },
    { zone: 'LO2', code: 'K2.1' },
    { zone: 'LO2', code: 'K2.2' },
    { zone: 'LO2', code: 'K2.3' },
    { zone: 'LO2', code: 'K2.4' },
    { zone: 'LO2', code: 'K2.5' },
    { zone: 'LO2', code: 'K2.6' },
    { zone: 'LO2', code: 'K2.7' },
    { zone: 'LO2', code: 'K2.8' },
    { zone: 'LO2', code: 'K2.9' },
    { zone: 'LO2', code: 'K2.10' },
    { zone: 'LO2', code: 'K2.11' },
    { zone: 'LO2', code: 'K2.12' },
    { zone: 'LO3', code: 'K3.1' },
    { zone: 'LO3', code: 'K3.2' },
    { zone: 'LO3', code: 'K3.3' },
    { zone: 'LO3', code: 'K3.4' },
    { zone: 'LO3', code: 'K3.5' },
    { zone: 'LO3', code: 'K3.6' },
    { zone: 'LO3', code: 'K3.7' },
    { zone: 'LO3', code: 'K3.8' },
    { zone: 'LO3', code: 'K3.9' },
    { zone: 'LO3', code: 'K3.10' },
    { zone: 'LO3', code: 'K3.11' },
    { zone: 'LO3', code: 'K3.12' },
    { zone: 'LO4', code: 'K4.1' },
    { zone: 'LO4', code: 'K4.2' },
    { zone: 'LO4', code: 'K4.3' },
    { zone: 'LO4', code: 'K4.4' },
    { zone: 'LO4', code: 'K4.5' },
    { zone: 'LO4', code: 'K4.6' },
    { zone: 'LO4', code: 'K4.7' },
    { zone: 'LO4', code: 'K4.8' },
    { zone: 'LO4', code: 'K4.9' },
    { zone: 'LO4', code: 'K4.10' },
    { zone: 'LO4', code: 'K4.11' },
    { zone: 'LO4', code: 'K4.12' },
    { zone: 'LO5', code: 'K5.1' },
    { zone: 'LO5', code: 'K5.2' },
    { zone: 'LO5', code: 'K5.3' },
    { zone: 'LO5', code: 'K5.4' },
    { zone: 'LO5', code: 'K5.5' },
    { zone: 'LO5', code: 'K5.6' },
    { zone: 'LO5', code: 'K5.7' },
    { zone: 'LO5', code: 'K5.8' },
    { zone: 'LO5', code: 'K5.9' },
    { zone: 'LO6', code: 'K6.1' },
    { zone: 'LO6', code: 'K6.2' },
    { zone: 'LO6', code: 'K6.3' },
    { zone: 'LO6', code: 'K6.4' },
    { zone: 'LO6', code: 'K6.5' },
    { zone: 'LO6', code: 'K6.6' },
    { zone: 'LO6', code: 'K6.7' },
    { zone: 'LO6', code: 'K6.8' },
    { zone: 'LO7', code: 'K7.1' },
    { zone: 'LO7', code: 'K7.2' },
    { zone: 'LO7', code: 'K7.3' },
    { zone: 'LO7', code: 'K7.4' },
    { zone: 'LO7', code: 'K7.5' },
    { zone: 'LO7', code: 'K7.6' },
    { zone: 'LO7', code: 'K7.7' },
    { zone: 'LO7', code: 'K7.8' },
    { zone: 'LO8', code: 'K8.1' },
    { zone: 'LO8', code: 'K8.2' },
    { zone: 'LO8', code: 'K8.3' },
    { zone: 'LO8', code: 'K8.4' },
    { zone: 'LO8', code: 'K8.5' },
    { zone: 'LO8', code: 'K8.6' },
    { zone: 'LO8', code: 'K8.7' },
    { zone: 'LO8', code: 'K8.8' },
    { zone: 'LO9', code: 'K9.1' },
    { zone: 'LO9', code: 'K9.2' },
    { zone: 'LO9', code: 'K9.3' },
    { zone: 'LO9', code: 'K9.4' },
    { zone: 'LO9', code: 'K9.5' },
    { zone: 'LO9', code: 'K9.6' },
    { zone: 'LO9', code: 'K9.7' },
    { zone: 'LO9', code: 'K9.8' },
  ],
};

const khotd1: WarehouseBaseline = {
  maKho: 'KHOTD1',
  tenKho: 'Kho trữ đông 1',
  zones: [
    { zone: 'LO1', tenLo: 'LÔ 1' },
    { zone: 'LO2', tenLo: 'LÔ 2' },
    { zone: 'LO3', tenLo: 'LÔ 3' },
    { zone: 'LO4', tenLo: 'LÔ 4' },
    { zone: 'LO5', tenLo: 'LÔ 5' },
    { zone: 'LO6', tenLo: 'LÔ 6' },
  ],
  slots: [
    { zone: 'LO1', code: 'K1.1' },
    { zone: 'LO1', code: 'K1.2' },
    { zone: 'LO1', code: 'K1.3' },
    { zone: 'LO1', code: 'K1.4' },
    { zone: 'LO1', code: 'K1.5' },
    { zone: 'LO1', code: 'K1.6' },
    { zone: 'LO1', code: 'K1.7' },
    { zone: 'LO1', code: 'K1.8' },
    { zone: 'LO2', code: 'K2.1' },
    { zone: 'LO2', code: 'K2.2' },
    { zone: 'LO2', code: 'K2.3' },
    { zone: 'LO2', code: 'K2.4' },
    { zone: 'LO2', code: 'K2.5' },
    { zone: 'LO2', code: 'K2.6' },
    { zone: 'LO3', code: 'K3.1' },
    { zone: 'LO3', code: 'K3.2' },
    { zone: 'LO3', code: 'K3.3' },
    { zone: 'LO3', code: 'K3.4' },
    { zone: 'LO3', code: 'K3.5' },
    { zone: 'LO3', code: 'K3.6' },
    { zone: 'LO3', code: 'K3.7' },
    { zone: 'LO3', code: 'K3.8' },
    { zone: 'LO4', code: 'K4.1' },
    { zone: 'LO4', code: 'K4.2' },
    { zone: 'LO4', code: 'K4.3' },
    { zone: 'LO4', code: 'K4.4' },
    { zone: 'LO4', code: 'K4.5' },
    { zone: 'LO4', code: 'K4.6' },
    { zone: 'LO5', code: 'K5.1' },
    { zone: 'LO5', code: 'K5.2' },
    { zone: 'LO5', code: 'K5.3' },
    { zone: 'LO5', code: 'K5.4' },
    { zone: 'LO5', code: 'K5.5' },
    { zone: 'LO5', code: 'K5.6' },
    { zone: 'LO5', code: 'K5.7' },
    { zone: 'LO6', code: 'K6.1' },
    { zone: 'LO6', code: 'K6.2' },
    { zone: 'LO6', code: 'K6.3' },
    { zone: 'LO6', code: 'K6.4' },
  ],
};

const khotd2: WarehouseBaseline = {
  maKho: 'KHOTD2',
  tenKho: 'Kho trữ đông 2',
  zones: [
    { zone: 'LO1', tenLo: 'LÔ 1' },
    { zone: 'LO2', tenLo: 'LÔ 2' },
    { zone: 'LO3', tenLo: 'LÔ 3' },
    { zone: 'LO4', tenLo: 'LÔ 4' },
  ],
  slots: [
    { zone: 'LO1', code: 'K1.1' },
    { zone: 'LO1', code: 'K1.2' },
    { zone: 'LO1', code: 'K1.3' },
    { zone: 'LO1', code: 'K1.4' },
    { zone: 'LO1', code: 'K1.5' },
    { zone: 'LO1', code: 'K1.6' },
    { zone: 'LO1', code: 'K1.7' },
    { zone: 'LO1', code: 'K1.8' },
    { zone: 'LO2', code: 'K2.1' },
    { zone: 'LO2', code: 'K2.2' },
    { zone: 'LO2', code: 'K2.3' },
    { zone: 'LO2', code: 'K2.4' },
    { zone: 'LO2', code: 'K2.5' },
    { zone: 'LO2', code: 'K2.6' },
    { zone: 'LO3', code: 'K3.1' },
    { zone: 'LO3', code: 'K3.2' },
    { zone: 'LO3', code: 'K3.3' },
    { zone: 'LO3', code: 'K3.4' },
    { zone: 'LO3', code: 'K3.5' },
    { zone: 'LO3', code: 'K3.6' },
    { zone: 'LO3', code: 'K3.7' },
    { zone: 'LO4', code: 'K4.1' },
    { zone: 'LO4', code: 'K4.2' },
    { zone: 'LO4', code: 'K4.3' },
    { zone: 'LO4', code: 'K4.4' },
    { zone: 'LO4', code: 'K4.5' },
    { zone: 'LO4', code: 'K4.6' },
  ],
};

const hd1: WarehouseBaseline = {
  maKho: 'HD1',
  tenKho: 'Hầm đông 1',
  zones: [
    { zone: 'LO1', tenLo: 'LÔ 1' },
    { zone: 'LO2', tenLo: 'LÔ 2' },
  ],
  slots: [
    { zone: 'LO1', code: 'K1.1' },
    { zone: 'LO1', code: 'K1.2' },
    { zone: 'LO1', code: 'K1.3' },
    { zone: 'LO1', code: 'K1.4' },
    { zone: 'LO1', code: 'K1.5' },
    { zone: 'LO1', code: 'K1.6' },
    { zone: 'LO2', code: 'K2.1' },
    { zone: 'LO2', code: 'K2.2' },
    { zone: 'LO2', code: 'K2.3' },
    { zone: 'LO2', code: 'K2.4' },
    { zone: 'LO2', code: 'K2.5' },
    { zone: 'LO2', code: 'K2.6' },
  ],
};

const hd2: WarehouseBaseline = {
  maKho: 'HD2',
  tenKho: 'Hầm đông 2',
  zones: [
    { zone: 'LO1', tenLo: 'LÔ 1' },
    { zone: 'LO2', tenLo: 'LÔ 2' },
  ],
  slots: [
    { zone: 'LO1', code: 'K1.1' },
    { zone: 'LO1', code: 'K1.2' },
    { zone: 'LO1', code: 'K1.3' },
    { zone: 'LO1', code: 'K1.4' },
    { zone: 'LO1', code: 'K1.5' },
    { zone: 'LO1', code: 'K1.6' },
    { zone: 'LO1', code: 'K1.7' },
    { zone: 'LO1', code: 'K1.8' },
    { zone: 'LO2', code: 'K2.1' },
    { zone: 'LO2', code: 'K2.2' },
    { zone: 'LO2', code: 'K2.3' },
    { zone: 'LO2', code: 'K2.4' },
    { zone: 'LO2', code: 'K2.5' },
    { zone: 'LO2', code: 'K2.6' },
    { zone: 'LO2', code: 'K2.7' },
    { zone: 'LO2', code: 'K2.8' },
  ],
};

const khopl: WarehouseBaseline = {
  maKho: 'KHOPL',
  tenKho: 'Phòng phụ liệu',
  zones: [
    { zone: 'DAUCHIEN-LO1', tenLo: 'Dầu chiên · LÔ 1' },
    { zone: 'DAUCHIEN-LO2', tenLo: 'Dầu chiên · LÔ 2' },
    { zone: 'NHA-LO1', tenLo: 'Nha · LÔ 1' },
  ],
  slots: [
    { zone: 'DAUCHIEN-LO1', code: 'K1.1' },
    { zone: 'DAUCHIEN-LO1', code: 'K1.2' },
    { zone: 'DAUCHIEN-LO1', code: 'K1.3' },
    { zone: 'DAUCHIEN-LO1', code: 'K1.4' },
    { zone: 'DAUCHIEN-LO1', code: 'K1.5' },
    { zone: 'DAUCHIEN-LO1', code: 'K1.6' },
    { zone: 'DAUCHIEN-LO1', code: 'K1.7' },
    { zone: 'DAUCHIEN-LO1', code: 'K1.8' },
    { zone: 'DAUCHIEN-LO1', code: 'K1.9' },
    { zone: 'DAUCHIEN-LO1', code: 'K1.10' },
    { zone: 'DAUCHIEN-LO1', code: 'K1.11' },
    { zone: 'DAUCHIEN-LO1', code: 'K1.12' },
    { zone: 'DAUCHIEN-LO1', code: 'K1.13' },
    { zone: 'DAUCHIEN-LO2', code: 'K2.1' },
    { zone: 'DAUCHIEN-LO2', code: 'K2.2' },
    { zone: 'DAUCHIEN-LO2', code: 'K2.3' },
    { zone: 'DAUCHIEN-LO2', code: 'K2.4' },
    { zone: 'DAUCHIEN-LO2', code: 'K2.5' },
    { zone: 'DAUCHIEN-LO2', code: 'K2.6' },
    { zone: 'DAUCHIEN-LO2', code: 'K2.7' },
    { zone: 'DAUCHIEN-LO2', code: 'K2.8' },
    { zone: 'DAUCHIEN-LO2', code: 'K2.9' },
    { zone: 'DAUCHIEN-LO2', code: 'K2.10' },
    { zone: 'DAUCHIEN-LO2', code: 'K2.11' },
    { zone: 'DAUCHIEN-LO2', code: 'K2.12' },
    { zone: 'DAUCHIEN-LO2', code: 'K2.13' },
    { zone: 'NHA-LO1', code: 'K1.1' },
    { zone: 'NHA-LO1', code: 'K1.2' },
    { zone: 'NHA-LO1', code: 'K1.3' },
    { zone: 'NHA-LO1', code: 'K1.4' },
    { zone: 'NHA-LO1', code: 'K1.5' },
    { zone: 'NHA-LO1', code: 'K1.6' },
    { zone: 'NHA-LO1', code: 'K1.7' },
    { zone: 'NHA-LO1', code: 'K1.8' },
    { zone: 'NHA-LO1', code: 'K1.9' },
    { zone: 'NHA-LO1', code: 'K1.10' },
    { zone: 'NHA-LO1', code: 'K1.11' },
    { zone: 'NHA-LO1', code: 'K1.12' },
  ],
};

export const WAREHOUSE_BASELINES: WarehouseBaseline[] = [khotp, khotd1, khotd2, hd1, hd2, khopl];

export const getBaseline = (maKho?: string): WarehouseBaseline | undefined =>
  WAREHOUSE_BASELINES.find((b) => b.maKho === maKho);
